let state={persona:null,stage:0,sat:70,eff:50,time:12,emotion:60,total:0,max:0,branch:'own',skills:{'Empathy':0,'Problem Solving':0,'Journey Awareness':0,'Service Recovery':0,'Digital CX':0,'Measurement':0},skillMax:{'Empathy':0,'Problem Solving':0,'Journey Awareness':0,'Service Recovery':0,'Digital CX':0,'Measurement':0}};
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1300);}
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
function emotionInfo(v){if(v>=85)return['🤩','مبسوط جدًا'];if(v>=70)return['😄','سعيد'];if(v>=55)return['🙂','مطمّن'];if(v>=40)return['😐','محايد'];if(v>=25)return['😠','منزعج'];return['🤬','غاضب جدًا'];}
function updateTop(){state.sat=clamp(state.sat,0,100);state.eff=clamp(state.eff,0,100);state.time=Math.max(1,state.time);state.emotion=clamp(state.emotion,0,100);$('satTop').textContent=Math.round(state.sat);$('effTop').textContent=Math.round(state.eff);$('timeTop').textContent=Math.round(state.time)+'m';const[f,l]=emotionInfo(state.emotion);$('emotionFace').textContent=f;$('emotionLabel').textContent=l;$('emotionBar').style.width=state.emotion+'%';const totalStages=scenarios.length+1;$('progressBar').style.width=Math.min(100,(state.stage/totalStages)*100)+'%';}
function goPersona(){show('personaScreen');$('stagePill').textContent='اختيار Persona';renderPersonas();}
function renderPersonas(){$('personaGrid').innerHTML='';personas.forEach(p=>{const b=document.createElement('button');b.className='persona';b.innerHTML=`<span class="icon">${p.icon}</span><b>${p.name}</b><small>${p.desc}</small>`;b.onclick=()=>{state.persona=p;document.querySelectorAll('.persona').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('personaStart').disabled=false;toast('تم اختيار '+p.name);};$('personaGrid').appendChild(b);});}
function startSimulation(){if(!state.persona)return;state.stage=0;$('stagePill').textContent='1/'+(scenarios.length+1);show('scenarioScreen');renderScenario(scenarios[0]);}
function renderScenario(sc){$('scenarioScreen').classList.toggle('crisis',!!sc.crisis);$('scenarioTag').textContent=sc.tag;$('scenarioTitle').textContent=sc.title;$('scenarioSub').textContent=sc.sub;$('scenarioText').innerHTML=typeof sc.text==='function'?sc.text(state.persona):sc.text;$('choices').innerHTML='';$('impactBox').classList.remove('show');$('nextBtn').classList.add('hidden');sc.choices.forEach(c=>{const b=document.createElement('button');b.className='choice';b.textContent=c.t;b.onclick=()=>applyChoice(c,b,sc);$('choices').appendChild(b);});updateTop();}
function signed(v,suffix=''){return(v>0?'+':'')+v+suffix;}
function applyChoice(c,btn,sc){document.querySelectorAll('.choice').forEach(x=>x.classList.add('lock'));btn.classList.add(c.grade);state.sat+=c.sat;state.eff+=c.eff;state.time+=c.time;state.emotion+=c.emotion;state.total+=c.pts;state.max+=10;if(c.branch)state.branch=c.branch;state.skills[c.skill]=(state.skills[c.skill]||0)+c.pts;state.skillMax[c.skill]=(state.skillMax[c.skill]||0)+10;$('impactSat').textContent=signed(c.sat);$('impactEff').textContent=signed(c.eff);$('impactTime').textContent=signed(c.time,'m');$('feedback').textContent=(c.grade==='good'?'✅ ':c.grade==='bad'?'⚠️ ':'💡 ')+c.fb;$('learning').innerHTML='<b>تعلّم:</b> '+c.learn;$('impactBox').classList.add('show');$('nextBtn').classList.remove('hidden');$('nextBtn').textContent=(state.stage===scenarios.length?'شوف النتيجة 🏆':'التالي ←');updateTop();}
function nextStage(){state.stage++;if(state.stage<scenarios.length){$('stagePill').textContent=(state.stage+1)+'/'+(scenarios.length+1);renderScenario(scenarios[state.stage]);return;}if(state.stage===scenarios.length){const fin=finalBranches[state.branch]||finalBranches.own;$('stagePill').textContent=(state.stage+1)+'/'+(scenarios.length+1);renderScenario({...fin,crisis:true});return;}finish();}
function finish(){show('resultScreen');$('stagePill').textContent='النتيجة';$('progressBar').style.width='100%';let score=Math.round((state.total/state.max)*100);score=clamp(score,0,100);$('finalScore').textContent=score+'/100';let rank,msg;if(score>=90){rank='👑 Customer Hero';msg='ممتاز جدًا. قراراتك بتوازن بين العميل، العملية، والنتيجة.';}else if(score>=75){rank='🏆 CX Champion';msg='وعي قوي جدًا بالـCustomer Experience ومبادئ الرحلة والـOwnership.';}else if(score>=60){rank='🥈 CX Specialist';msg='أساس جيد. عندك فرص واضحة لتحسين بعض قرارات الرحلة والـService Recovery.';}else{rank='🌱 CX Explorer';msg='اللعبة كشفت لك أهم مفاهيم CX اللي محتاج تركز عليها أكتر.';}$('finalRank').textContent=rank;$('finalMsg').textContent=msg;$('sumSat').textContent=Math.round(state.sat)+'/100';$('sumEff').textContent=Math.round(state.eff)+'/100';$('sumTime').textContent=Math.round(state.time)+' min';$('sumEmotion').textContent=emotionInfo(state.emotion)[0]+' '+emotionInfo(state.emotion)[1];renderSkills();}
function renderSkills(){$('skillsBox').innerHTML='';Object.keys(state.skills).forEach(k=>{const max=state.skillMax[k];if(!max)return;const pct=Math.round((state.skills[k]/max)*100);const d=document.createElement('div');d.className='skill';d.innerHTML=`<div class="skill-row"><span>${k}</span><span>${pct}%</span></div><div class="skillbar"><div style="width:${pct}%"></div></div>`;$('skillsBox').appendChild(d);});}
function restart(){state={persona:null,stage:0,sat:70,eff:50,time:12,emotion:60,total:0,max:0,branch:'own',skills:{'Empathy':0,'Problem Solving':0,'Journey Awareness':0,'Service Recovery':0,'Digital CX':0,'Measurement':0},skillMax:{'Empathy':0,'Problem Solving':0,'Journey Awareness':0,'Service Recovery':0,'Digital CX':0,'Measurement':0}};$('personaStart').disabled=true;$('stagePill').textContent='جاهز';updateTop();show('startScreen');}
updateTop();